---

fail_fast: false
minimum_pre_commit_version: "2.6.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
        exclude: "templates/.*"
      - id: mixed-line-ending
      #      - id: trailing-whitespace
      #- id: flake8

  # requires copywrite to be installed
  # brew tap hashicorp/tap
  # brew install hashicorp/tap/copywrite
  - repo: https://github.com/hashicorp/copywrite
    rev: v0.19.0 # Use any release tag
    hooks:
      - id: add-headers
        name: Add copyright headers
        description: Adds missing copyright headers to all source code files
        entry: copywrite
        args: [headers]

